module.exports = Object.freeze({

  mongodburl:'localhost:27017/arduinocommdb',

  ESP_STATES: [
    "STATE_READY",                "STATE_WIFI_CONNECT",           "STATE_WIFI_ACTIVE",
    "STATE_ACCESS_POINT_CONNECT", "STATE_ACCESS_POINT_ACTIVE",    "STATE_SLEEP",
    "STATE_BOOTING",              "STATE_REQUEST_CONFIG",         "STATE_RESPONSE_CONFIG_DETAILS",
    "STATE_CONFIG_UPDATED",       "STATE_ACTIVE",                 "STATE_PASSIVE",
    "STATE_ONLINE",               "STATE_OFFLINE",                "STATE_OTA_AVAILABLE",
    "STATE_INIT_OTA"
  ],

  STATE_READY: 0,
  STATE_WIFI_CONNECT: 1,
  STATE_WIFI_ACTIVE: 2,
  STATE_ACCESS_POINT_CONNECT: 3,
  STATE_ACCESS_POINT_ACTIVE: 4,
  STATE_SLEEP: 5,
  STATE_BOOTING: 6,
  STATE_REQUEST_CONFIG: 7,
  STATE_RESPONSE_CONFIG_DETAILS: 8,
  STATE_CONFIG_UPDATED: 9,
  STATE_ACTIVE: 10,
  STATE_PASSIVE: 11,
  STATE_ONLINE: 12,
  STATE_OFFLINE: 13,
  STATE_OTA_AVAILABLE: 14,
  STATE_INIT_OTA: 15

});